version: '3.4'

services:
  cfs-pi:
    privileged: true
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
      network: host
      args:
        - VARIANT=20.04
    image: cfs-pi:latest
    container_name: cfs-pi
    working_dir: /workspace
    stdin_open: true
    tty: true
    ulimits:
        nproc: 2048
        rtprio: 99
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    sysctls:
        fs.mqueue.msg_max: 1024
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
  
