version: '3.4'

services:
  cfs-pi:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
      network: host
      args:
        - VARIANT=22.04
    image: cfs-pi:latest
    container_name: cfs-pi
    working_dir: /workspace
    environment:
      - RPI_PASSWORD_FILE=/run/secrets/rpi_password
      - RPI_USERNAME=pi
      - RPI_HOSTNAME=169.254.251.102
    secrets:
      - rpi_password
      # * The following are optional but useful
      - ssh_public_key
      - ssh_private_key
      - gitconfig
    stdin_open: true
    tty: true
    ulimits:
        nproc: 2048
        rtprio: 99
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    sysctls:
        fs.mqueue.msg_max: 1024
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
secrets:
    rpi_password:
      file: ./rpi_password.txt
    # * The following are optional but useful
    ssh_public_key:
      file: ~/.ssh/id_rsa.pub
    ssh_private_key:
      file: ~/.ssh/id_rsa
    gitconfig:
      file: ~/.gitconfig-personal
